# vim:ft=ruby:
#
cask_args appdir: '/Applications'

tap "derailed/k9s"
tap "github/gh"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "osx-cross/avr"
tap "px4/px4"
tap "thoughtbot/formulae"
tap "teamookla/speedtest"

brew "ansifilter"
brew "autoconf"
brew "automake"
brew "bats"
brew "coreutils"
brew "libtool"
brew "libyaml"
brew "libpq"
brew "openssl@1.1"
brew "readline"
brew "unixodbc"
brew "asdf"
brew "autoenv"
brew "avrdude"
brew "awscli"
brew "clipper", restart_service: true
brew "speedtest", force: true
brew "cmatrix"
brew "colordiff"
brew "ctags"
brew "curl"
brew "cloc"
brew "dfu-programmer"
brew "dfu-util"
brew "doctl"
brew "exa"
brew "fasd"
brew "fd"
brew "ffmpeg"
brew "forego"
brew "fzf"
brew "gawk"
brew "gcc"
brew "git"
brew "git-crypt"
brew "git-delta"
brew "glide"
brew "gnupg"
brew "helm"
brew "httpie"
brew "hub"
brew "hugo"
brew "jq"
brew "k3d"
brew "kubernetes-cli"
brew "libxslt"
brew "markdown"
brew "mas"
brew "minikube"
brew "neovim", args: ["HEAD"]
brew "nomad"
brew "packer"
brew "pgformatter"
brew "pre-commit"
brew "rename"
brew "ripgrep"
brew "rke"
brew "ssh-copy-id"
brew "streamlink"
brew "terraform"
brew "terraform-docs"
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "trash"
brew "unzip"
brew "vault"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "derailed/k9s/k9s"
brew "github/gh/gh"
brew "goreleaser/tap/goreleaser"
brew "jesseduffield/lazygit/lazygit"
brew "osx-cross/avr/avr-gcc@8", link: true
brew "px4/px4/gcc-arm-none-eabi"
brew "thoughtbot/formulae/rcm"

cask "1password"
cask "alacritty"
cask "alfred"
cask "android-studio"
cask "dash"
cask "docker"
cask "dropshare"
cask "figma"
cask "firefox"
cask "font-anonymous-pro"
cask "font-fira-code"
cask "font-jetbrains-mono"
cask "font-roboto-mono"
cask "font-source-code-pro"
cask "font-space-mono"
cask "google-chrome"
cask "hyper"
cask "imageoptim"
cask "insomnia"
cask "iterm2"
cask "kaleidoscope"
cask "keybase"
cask "kitty"
cask "macvim"
cask "ngrok"
cask "now"
cask "permute"
cask "pgadmin4"
cask "postman"
cask "rectangle"
cask "sequel-pro"
cask "sketch"
cask "spectrum"
cask "spotify"
cask "transmit"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"

mas "Calcbot", id: 931657367
mas "Deliveries", id: 924726344
mas "Reeder", id: 1449412482
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
