BASE="$HOME/.zsh"

load_all_files_in() {
  for file in "$BASE/$1"/*.zsh; do
    source "$file"
  done
}

load_all_files_in ""

source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/.localrc ] && source ~/.localrc

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

eval "$(rbenv init -)"
# added by travis gem

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/drew/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/drew/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/drew/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/drew/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
