set nocompatible

" Leader
let mapleader = " "
" exit to normal mode with 'jj'
inoremap jj <ESC>

set background=dark

filetype indent plugin on

"Enable Syntax Highlighting
syntax on

set hidden "allows you to resuse the same window and switch buffer
set wildmenu "better command-line execution
set showcmd "Show partials commands in the last time of the screen
set hlsearch "Highlight searches
set ignorecase "Use case insensitive search
set smartcase
set backspace=indent,eol,start "allow backspacing over autoindent
set autoindent
set nostartofline
set ruler
set laststatus=2
set confirm
set visualbell
set t_vb=
set mouse=a
set cmdheight=2
set number
set notimeout ttimeout ttimeoutlen=200
set pastetoggle=<F11>

" Display extra whitespace
set list listchars=tab:»·,trail:·

set shiftwidth=2
set softtabstop=2
set expandtab

map Y y$

nnoremap <C-L> :nohl<CR><C-L>

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l


