#!/bin/bash
# vim: tw=0
# from https://github.com/gabebw/dotfiles/blob/main/install.sh

set -eo pipefail

source ./bin/common

if ["$OSTYPE" = "darwin"] ; then
  info "Configuring MacOS..."
  stay_awake_while ./macos
fi
