#!/bin/bash
# vim: tw=0
# from https://github.com/gabebw/dotfiles/blob/main/install.sh

set -eo pipefail

source ./bin/common

info "Installing ASDF version managing..."
# Load asdf (before setup scripts) in case it's the first time installing it
export NODEJS_CHECK_SIGNATURES=no
source /usr/local/opt/asdf/asdf.sh

stay_awake_while asdf install
